import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Header from "@/laduny/components/Header";
import Footer from "@/laduny/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Laduny Computer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <ChakraProvider>
          <Header />
          <main className="w-full min-h-screen">{children}</main>
          <Footer />
        </ChakraProvider>
      </body>
    </html>
  );
}
